<?php

namespace Database\Seeders;

use App\Models\EquipmentAssetManufacturer;
use Illuminate\Database\Seeder;
use Carbon\Carbon;
use Faker\Generator as Faker;

use App\Models\Gas;

class EquipmentAssetManufacturerSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run(Faker $faker)
    {
        /**
         * Create the default admin user
         */

        $manufacturers = [
            '3M',
            'A.O. SMITH',
            'AAADM',
            'AAON',
            'ABB',
            'ABB POWER T&D CO',
            'ABSOCOLD',
            'ABU HOSAN',
            'ACCUCOLD',
            'ACL-FILCO',
            'ACME INDUSTRIES',
            'ADDISON',
            'ADMIRAL',
            'ADVANCED SPECIALTY GASES',
            'AEG',
            'AHT',
            'AIR COOLED',
            'AIR PRODUCTS',
            'AIR ROVER',
            'AIRE FLOW',
            'AIREASE',
            'AIREDALE',
            'AIRFAN',
            'AIRFLOW',
            'AIRGAS',
            'AIRSYS',
            'AIR-TEMP',
            'AKAI',
            'ALERTON',
            'ALLEN BRADLEY',
            'ALLIED',
            'ALLIED CHEMICAL',
            'ALLIED SIGNAL',
            'ALTHAM-SAVOISIENVE',
            'ALSTOM',
            'ALTO SHAAM',
            'ALTON',
            'AMANA',
            'AMEREX',
            'AMERICAN PANEL',
            'AMERICAN RARE GASES',
            'AMERICAN STANDARD',
            'AMERICANA',
            'AMERITEK',
            'AMES',
            'AMS',
            'AMTEKCO',
            'AMTROL CYLINDER',
            'ANNEXAIR',
            'APISTE',
            'APOLLO/CONBRACO',
            'APPION',
            'APPLIED ENGINEERING',
            'APW MCLEAN',
            'ARCOAIRE',
            'ARCTIC GLACIER',
            'ARCTICHILL',
            'AREVA',
            'ARI',
            'ARIZON-JOHNSON',
            'ARMSTRONG',
            'ARNEG',
            'ARROW AIR DRYER',
            'ARTIC AIR',
            'ARTIC STAR',
            'ASEA BROWN BOVERI',
            'ATC GROUP',
            'ATLANTIC FOOD BARS',
            'ATLAS METAL IND',
            'ATS',
            'AQUA SNAP',
            'AVANTCO',
            'AVANTI',
            'AVERA',
            'AWALGULF MFG',
            'B.D. PAYNE',
            'BAC',
            'BACHARACH',
            'BACKFLOW DIRECT',
            'BALTIMORE',
            'BALTIMORE AIR COIL',
            'BARD',
            'BARKER',
            'BARRON',
            'BAY MANUFACTURING',
            'BDD',
            'BDP',
            'BERKLEY',
            'BEVAIR',
            'BEVERAGE AIR',
            'BILOFF',
            'BITZER',
            'BLACK AND DECKER',
            'BLENDTEC',
            'BOHN',
            'BOHN/HEATCRAFT',
            'BOHSEI',
            'BORG WARNER',
            'BORGEN',
            'BREYERS',
            'BROWN BOVERI CORP',
            'BRYANT',
            'BUNN',
            'C NELSON',
            'CALHOUN AND BOXON',
            'CALIFORNIA CONTROLLED ATMOSPHERE',
            'CANADA POWER PRODUCTS',
            'CANCOIL THERMAL CORP',
            'CAPTIVEAIRE',
            'CARAVELL',
            'CARL',
            'CARLYLE',
            'CARNOT REFRIGERATION',
            'CARRIER',
            'CARTER',
            'CARTERHOF',
            'CASH ACME',
            'CATTABRIGA',
            'CBISS',
            'CENTAUR',
            'CENTURY',
            'CES',
            'CHANDLER',
            'CHARGE',
            'CHATTANOOGA CORP',
            'CHEFMATE',
            'CHELSEA VOGT',
            'CHESTER JENSEN',
            'CHILLGARD',
            'CHRYSLER',
            'CIAM',
            'CIAT',
            'CIATESA',
            'CIMCO LEWIS',
            'CLABO',
            'CLA-VAL',
            'CLIMATE CONTROL',
            'CLIMATE MASTER',
            'CLIMATROL',
            'CLOVER',
            'COBEL TECH',
            'COLD MASTERS',
            'COLD PACK',
            'COLDSTREAM',
            'COLDTECH',
            'COLDZONE',
            'COLE ENGINEERING',
            'COLEMAN',
            'COLUMBUS SHOWCASE',
            'COMFORT AIR',
            'COMFORT AIRE',
            'COMFORTMAKER',
            'COMP',
            'COMPU-AIRE',
            'COM-TROL',
            'CON PAK',
            'CONBRACO',
            'CONCORDE',
            'CONTEMPO',
            'CONTINENTAL',
            'COOL CABI',
            'COOLINE',
            'COOLPOINT',
            'COOLTECH',
            'COOLWAVE',
            'COOPER POWER SYSTEMS',
            'COPELAND',
            'COPELAND DISCUS',
            'CORDLEY',
            'CORNELIUS',
            'CORRECTEMP',
            'COST POINT',
            'COURRIER',
            'COYOD',
            'CPC',
            'CPR INDUSTRIES',
            'CREAMISER',
            'CROSLEY',
            'CRYSTAL TIPS',
            'CSA',
            'CSC WORLDWIDE',
            'CUMMINS PACIFIC',
            'CUSTOM BUILT',
            'CULTER-HAMMER',
            'DAIKIN',
            'DANBY',
            'DANTHERM',
            'DATA/AIRE',
            'DAY AND NIGHT',
            'DAYTON',
            'DELFIELD',
            'DELL SMITH',
            'DELTA AIRE',
            'DIEBOLD',
            'DIGITAL',
            'DILO',
            'DIPLOMAT',
            'DISPLAYMOR',
            'DIXIE NARCO',
            'DUCANE',
            'DUNHAM-BUSH',
            'EAGAN',
            'EATON',
            'EBCO',
            'EDGESTAR',
            'EDISON SOURCE',
            'EDWARDS',
            'EDYS',
            'ELECTRICAL EQUIPMENT INC',
            'ELECTROLUX',
            'ELKAY',
            'EMC',
            'EMERSON',
            'EMI',
            'ENERGY LABS',
            'ENGINEERED REFRIGERATION SYSTEMS',
            'ENODIS',
            'ENVIROMASTER INTERNATIONAL',
            'ENVIRONMENTAL TECTONICS CORP',
            'ESCO',
            'ESPEC',
            'ESTATE',
            'ETL',
            'EVAPCO',
            'EVEREST',
            'EXCELLENCE',
            'FACT I',
            'FBD',
            'FEBCO',
            'FEDDERS UNITARY PRODUCTS',
            'FEDERAL',
            'FELIX STORCH',
            'FES',
            'FHP MANUFACTURING',
            'FIELDPIECE',
            'FILTRINE',
            'FISHER SCIENTIFIC',
            'FLAKICE',
            'FLCOLD',
            'FLOMATIC',
            'FLORALINE',
            'FOGEL',
            'FOLLETT',
            'FOOD SUPPLIES',
            'FORMA SCIENTIFIC',
            'FOSTER',
            'FRANKLIN CHEF',
            'FRANSCOLD',
            'FRICK',
            'FRIEDRICH',
            'FRIGID COIL',
            'FRIGIDAIRE',
            'FROZEN BEVERAGE DISPENSERS',
            'FUJITSU',
            'FURNAS',
            'G&W',
            'GABER',
            'GALAXY',
            'GALLANZ',
            'GE',
            'GEA SEARLE',
            'GEC ALSTHOM',
            'GE-HITACHI',
            'GENERAL ELECTRIC',
            'GENESIS',
            'GEORGE IND',
            'GHV REFRIGERATION',
            'GIBSON',
            'GLOBAL',
            'GOLD STAR',
            'GOODMAN',
            'GOULD',
            'GOVERNAIR',
            'GRAINGER',
            'GRANDAIRE',
            'GREE',
            'GREEN AND COOL',
            'GREENHECK',
            'GUARDIAN',
            'HAIER',
            'HALOGARD',
            'HALSEY TAYLOR',
            'HAMILTON BEACH',
            'HAMPTON BAY',
            'HANBELL',
            'HANKISON',
            'HARTFORD COMP',
            'HASKRIS',
            'HAWS',
            'HEAT CONTROLLER INC',
            'HEATCRAFT REFRIGERATION',
            'HEIL',
            'HELMER',
            'HENNY PENNY',
            'HERSEY',
            'HILL EMHART',
            'HILL EXCELLENCE',
            'HILL-PHOENIX',
            'HITACHI',
            'HITACHI (HVB)',
            'HLA',
            'HOBART',
            'HOLIDAY',
            'HOME CITY ICE',
            'HONEYWELL',
            'HOSHIZAKI',
            'HOTPOINT',
            'HOUSEHOLD',
            'HOWARD MCCRAY',
            'HOWE',
            'HTP',
            'HTPG',
            'HULL',
            'HUSSMAN MANUFACTURING',
            'HUSSMANN',
            'HVB',
            'HYDRO MISER',
            'IBIZA',
            'ICEE',
            'ICEE-O-MATIC',
            'ICP',
            'IGLOO',
            'INDUSTRIAL COLD STORAGE',
            'INGERSOLL RAND',
            'INGLIS',
            'INNOVENT',
            'INNOWAVE',
            'INTELLIPAK',
            'INTER-CITY PRODUCTS CORP',
            'INTERNATIONAL COMFORT PRODUCTS',
            'INVERTER',
            'IRLDS',
            'ISLAND',
            'JAM',
            'JIMENEX COLD TECH',
            'JOHNSON CONTROL',
            'JORDAN',
            'JOSLYN',
            'JSI STORE FIXTURES',
            'KAIRAK',
            'KARLYLE',
            'KASON',
            'KCPL',
            'KEARNEY',
            'KEEPRITE',
            'KELVINATOR',
            'KENMORE',
            'KETEMA',
            'KIDDIE FIRE EXTINGUISHER',
            'KILLION',
            'KIMMEL MOTZ',
            'KINETICO',
            'KIRKLAND',
            'KITCHENAID',
            'KLIXON',
            'KLOPPENBERG',
            'KNIGHT',
            'KOCH',
            'KOLPAK',
            'KOOL-IT',
            'KRACK',
            'KRATHCO',
            'KYSOR',
            'KYSOR WARREN',
            'L.P. CONTROLLED',
            'LABCONOCO',
            'LABREPCO',
            'LANCER',
            'LARKIN',
            'LEADER',
            'LEER',
            'LENNOX',
            'LG',
            'LIEBERT',
            'LIMCO',
            'LINDE',
            'LOCKERBIE',
            'LUXAIRE',
            'LUXFER CYLINDERS',
            'MAGIC AIRE',
            'MAGIC CHEF',
            'MAMMOTH',
            'MAMMOTH LING',
            'MANEUROP',
            'MANITOWOC',
            'MARC CLIMATIC',
            'MARGAUX',
            'MARINELAND',
            'MARKET PLACE',
            'MARTEK',
            'MARVAIR',
            'MARVEL',
            'MASTER BILT',
            'MATHESON',
            'MAX',
            'MAYTAG',
            'MCCLEAN MIDWEST',
            'MCQUAY',
            'MCCALL',
            'MCCRAY',
            'MCGRAW EDISON',
            'MDV',
            'MEDIA',
            'MEI',
            'MELCO',
            'MERLIN GERIN',
            'MICRO FRIDGE',
            'MICRO MATIC',
            'MEDIEA',
            'MIDMARK',
            'MILE HIGH EQUIPMENT',
            'MIMET',
            'MIRACOOL',
            'MITSUBISHI',
            'MITSUBISHI ELECTRIC',
            'MITSUBISHI POWER PRODUCTS',
            'MODINE',
            'MONTGOMERY WARD',
            'MOTIVAIR',
            'MOVINCOOL',
            'MR SLIM',
            'MSA',
            'MUELLER',
            'MULTI STACK',
            'MUNTERS',
            'MURCO',
            'MYCOM',
            'N/A',
            'NATIONAL REFRIGERATION',
            'NCP',
            'ND',
            'NEPTUNE',
            'NESBITT',
            'NESLAB',
            'NEVINS REF',
            'NEW YORK SHOWCASE',
            'NEWMAN',
            'NWG',
            'NORCOLD',
            'NORDYNE',
            'NORLAKE',
            'NORRIS CYLINDER',
            'NOVELAIRE',
            'NSA',
            'NUCOOL',
            'O GENERAL',
            'OI ANALYTICAL',
            'OASIS',
            'OCTAGON',
            'OGENERAL',
            'OMNI TEMP',
            'OPTICOOL',
            'OSTER',
            'PACE',
            'PACIFIC REFRIGERATOR',
            'PANASONIC',
            'PARASENSE',
            'PARASYSTEMS',
            'PAYNE',
            'PEARL',
            'PEERLESS',
            'PERCIVAL',
            'PERRY',
            'PETRA',
            'PFANNENBERG-PANEL UNIT',
            'PHOENIX',
            'PHSI',
            'PIGGYBACK',
            'PINGUINO',
            'PNUMATECH',
            'POLAR',
            'POLYSCIENCE',
            'POMONA AIR',
            'POWERS',
            'PRAXAIR',
            'PREMIER',
            'PRESTAIR',
            'PRESTCOLD',
            'PRETEC',
            'PROCESS PRODUCTS',
            'PROCON',
            'PRODIGY',
            'PROTOCON',
            'PSB',
            'PURE HEALTH SOLUTIONS',
            'PURON',
            'PUTTY',
            'QBD COOLING',
            'QUENCH',
            'QUEST',
            'QUIETSIDE',
            'QUINCY',
            'R&D FIXTURES',
            'RAE',
            'RANDELL',
            'RCA',
            'RDI',
            'RECOLD',
            'REFCON',
            'REPACO',
            'REVCO SCIENTIFIC',
            'RHEEM',
            'RHOSS',
            'RITTAL',
            'RIVERSIDE REFRIGERATION',
            'ROPER',
            'ROYAL VENDORS',
            'RUSSELL',
            'RUUD',
            'RYSOR',
            'S&C',
            'SA',
            'SAMSUNG',
            'SANYO',
            'SCHNEIDER ELECTRIC',
            'SCOTSMAN',
            'SCR',
            'SEABREEZE',
            'SEARS',
            'SEASON FOUR',
            'SENTECH',
            'EXTON-CASLADE',
            'SG MERCHANDISING SOLUTIONS INC',
            'SIEMENS',
            'SILVER KING',
            'SINGER',
            'SKM',
            'SMARDT',
            'SNYDER',
            'SO-LOW',
            'SOURCE1',
            'SOUTH BEND',
            'SOUTHERN CASEARTS',
            'SOUTHERN ENGINEERING',
            'SOUTHERN STATES',
            'SOUTHERN STORE FIXTURES',
            'SOUTHLAND',
            'SOUTHWEST',
            'SPECIALTY',
            'SPECIALTY CHEMICAL',
            'SPECIALTY GASES',
            'SPECTRA GASES',
            'SPRECHER ENERGIE',
            'SQUARE D',
            'STAJAC',
            'STANDARD',
            'STANDEX',
            'STANLEY KNIGHT',
            'STAR',
            'STARCOLD',
            'STARK PRODUCTS',
            'STARRETT',
            'STERLING',
            'STOELTING',
            'STOKES',
            'STRUCTURAL CONCEPTS',
            'STULZ',
            'SUB ZERO',
            'SUMMIT',
            'SUNBEAM',
            'SUNROC',
            'TAPPAN',
            'TAYLOR',
            'TEAM COIL',
            'TECHNICAL SYSTEMS',
            'TECO',
            'TECUMSEH',
            'TELSTAR',
            'TEMPSTAR',
            'TEMTROL',
            'TEUMSEK',
            'THERMA STOR',
            'THERMAL CORE',
            'THERMAL ZONE',
            'THERMATRON',
            'THERMO SCIENTIFIC',
            'TONKA',
            'TOROMONT',
            'TOSHIBA',
            'TQ ENVIRONMENTAL',
            'TRANE',
            'TRANSITRAY',
            'TRAULSEN',
            'TRENTON',
            'TRI PALM',
            'TRI-COM',
            'TRITON',
            'TRUE',
            'TRYSERVICE',
            'TSI',
            'TURBO AIR',
            'TURBOCOR',
            'TURNER',
            'TYLER',
            'UBC GROUP',
            'U-LINE',
            'UNIMAX',
            'UNITARY PRODUCTS GROUP',
            'UNIVERSAL NOLAN',
            'UNKNOWN',
            'UTILITY',
            'VACOM REFRIGERATION SYSTEM',
            'VEN AIR SYSTEMS',
            'VENDO',
            'VERTIV',
            'VICTORY',
            'VILTER',
            'VOGT',
            'VOLLRATH',
            'VPS',
            'VSVA',
            'VWR SCIENTIFIC',
            'WAGNER',
            'WARREN',
            'WATERFURNACE',
            'WATERLOGIC',
            'WATTS',
            'WEATHER KING',
            'WEBER',
            'WELLS MFG',
            'WESTINGHOUSE',
            'WESTPOINT',
            'WETRACK',
            'WHIP',
            'WHIRLPOOL',
            'WHITMORE OXYGEN',
            'WILKINS',
            'WITT',
            'WOODS',
            'WOONGJIN CONWAY',
            'YALE',
            'YOKAGAWA',
            'YORK',
            'ZERO ZONE',
            'ZINSCO',
            'ZUMMO',
            'ZURN',
        ];

        foreach ($manufacturers as $manufacturer) {
            EquipmentAssetManufacturer::firstOrCreate(['name' => $manufacturer]);
        }
    }
}
