name: Laravel

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '7.4'


    - name: Checkout Git Repo
      uses: actions/checkout@v2


    - name: Setup Composer Dependencies
      run: composer install -q --no-ansi --no-dev --no-interaction --no-scripts --no-progress --prefer-dist


    - name: Copy Files to Remote
      uses: TylerOBrien/action-rsync@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        user: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        proxy_host: ${{ secrets.PROXY_HOST }}
        proxy_user: ${{ secrets.PROXY_USER }}
        proxy_key: ${{ secrets.PROXY_KEY }}
        proxy_disabled: ${{ secrets.PROXY_DISABLED }}
        source: ./
        destination: ./deploy


    - name: Deploy Laravel
      uses: TylerOBrien/action-laravel-deploy@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        user: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        proxy_host: ${{ secrets.PROXY_HOST }}
        proxy_user: ${{ secrets.PROXY_USER }}
        proxy_key: ${{ secrets.PROXY_KEY }}
        source: ./deploy

